### PR TITLE
refactor: replace hono with hono/tiny and replace zod with valibot

### LINKED ISSUE #536: [Feature]: Decrease overall bundle size
Current stats - Total Upload: `89.19 KiB / gzip: 25.73 KiB`

Decreasing bundle size has a meaningful impact on performance in Cloudflare Workers. (Serverless runtimes in general)

How can we do this?
- Remove / replace Zod
- Remove / replace Hono

### PR DESCRIPTION
**Pull request by ItsWendell**
## Description

Replaces `hono` with `hono/tiny` and replaces `zod` with `valibot` for a reduced bundle size and increased startup time. 

Fixes #536 

## How Has This Been Tested?

`pnpm test`

### CODE REVIEW

**Comment by ItsWendell** [comment]
I ran this through [https://bundlejs.com/?q=github%3Ahttps%3A%2F%2Fraw.githubusercontent.com%2FItsWendell%2Fturborepo-remote-cache-cloudflare%2Fmaster%2Fsrc%2Findex.ts&treeshake=%5B*%5D&config=%7B%22cdn%22%3A%22+https%3A%2F%2Fesm.sh%22%7D](https://bundlejs.com - build results?) and got result of Bundle size is 32.4 kB -> 11.2 kB (gzip)

**Review by AdiRishi — COMMENTED** [review]
Probably need to ensure all the unit tests in CI still pass.
You'll also need to commit the updated lockfile

**Comment by ItsWendell** [comment]
Bundle size is 32.5 kB -> 11.2 kB (gzip)

**Comment by AdiRishi** [comment]
@ItsWendell PR looks good, could you add a changeset file? You can do so by running `npx changeset`.
I think we can call this a `major` change. Feel free to add a nice description, it will be in the releases when I publish a new release.

FYI this is the makeup of your final build.
image

**Review by AdiRishi — DISMISSED** [review]

**Review by AdiRishi — APPROVED** [review]

**Pull request merged**
